In [2]:
#Q3: Create a 4×5 numpy array of all True’s.
import numpy as np
import pandas as pd
import math
p1=np.array([['true','true','true','true','true'],['true','true','true','true','true'],['true','true','true','true','true'],
             ['true','true','true','true','true']])
p1

array([['true', 'true', 'true', 'true', 'true'],
       ['true', 'true', 'true', 'true', 'true'],
       ['true', 'true', 'true', 'true', 'true'],
       ['true', 'true', 'true', 'true', 'true']], dtype='<U4')

In [3]:
p1.shape

(4, 5)

In [17]:
#Q4: Create an array of integers from 10 to 50 with with step of 3. Save the array in a. Replace all even numbers in a with -1.
a=np.arange(10,50,3)
a

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [15]:
#Q4: Create an array of integers from 10 to 50 with with step of 3. Save the array in a. Replace all even numbers in a with -1.
a=np.arange(10,50,3)
a[(a%2==0)]=-1
a

array([-1, 13, -1, 19, -1, 25, -1, 31, -1, 37, -1, 43, -1, 49])

In [22]:
#Q5: Create an one-dimensional array which includes odd numbers from 1 to 20.
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
#Q5- a: Change all numbers divisible by 3 into 0.
a=np.arange(1,20,2)
a[(a%3==0)]=0
a

array([ 1,  0,  5,  7,  0, 11, 13,  0, 17, 19])

In [30]:
#Q5- b: Change the array into a 2x5 matrix.
a.reshape(2,5)


array([[ 1,  0,  5,  7,  0],
       [11, 13,  0, 17, 19]])

In [35]:
#Q5- c: Convert all numbers of the third column into zero. Q6:
a=a.reshape(2,5)
a[:,3]=0
a

array([[ 1,  0,  5,  0,  0],
       [11, 13,  0,  0, 19]])

In [36]:
# a: Create an one-dimensional array, b1, which includes 9 numbers evenly spaced over 1.5 to 3.
b1=np.linspace(1.5,3,9)
b1

array([1.5   , 1.6875, 1.875 , 2.0625, 2.25  , 2.4375, 2.625 , 2.8125,
       3.    ])

In [44]:
#b: Create a 3x3 matrix, b2, which includes random numbers from Gaussian distribution with mean = 1, and sd = 0.75, seed = 1234.
np.random.seed(1234)
b2=np.random.normal(1,0.75,(3,3))
b2

array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

In [49]:
# d: What is the transpose of matrix b2?
b2.T

array([[1.35357637, 0.76551108, 1.64469131],
       [0.10676823, 0.45955845, 0.52260737],
       [2.07453023, 1.66537221, 1.01177228]])

In [51]:
#e: Convert b1 into a 3x3 matrix.
b1=np.linspace(1.5,3,9)
b1.reshape(3,3)


array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

In [52]:
#f: Calculate summation of b1 and b2.
b1

array([1.5   , 1.6875, 1.875 , 2.0625, 2.25  , 2.4375, 2.625 , 2.8125,
       3.    ])

In [53]:
b2

array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

In [60]:
b1=b1.reshape(3,3)
b1

array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

In [59]:
b1+b2

array([[2.85357637, 1.79426823, 3.94953023],
       [2.82801108, 2.70955845, 4.10287221],
       [4.26969131, 3.33510737, 4.01177228]])

In [61]:
# g: Calculate matrix multiplication of b1 and b2.
b1

array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

In [62]:
b2

array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

In [63]:
b1*b2

array([[2.03036456, 0.18017139, 3.88974417],
       [1.5788666 , 1.03400651, 4.05934475],
       [4.31731469, 1.46983323, 3.03531684]])

In [64]:
np.dot(b1,b2)

array([[ 6.40596071,  1.91554605,  7.81918396],
       [ 8.52308626,  2.52807145, 10.49200098],
       [10.64021182,  3.14059686, 13.16481801]])

In [65]:
#h: Call all numbers of b2 which are greater than mean of b2.
b2

array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

In [72]:
np.mean(b2)

1.0671541691431363

In [71]:
b2[(b2>np.mean(b2))]

array([1.35357637, 2.07453023, 1.66537221, 1.64469131])

In [73]:
#i: Scale matrix b2 using min-max scaling method. End of Code
b2

array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

In [74]:
np.min(b2)

0.1067682289701517

In [75]:
np.max(b2)

2.074530226319573